<?php
session_start();
include('../config.php');


$uname = $_SESSION['uname'];
if(!isset($_SESSION['uname']))
{
  header('Location:../logout.php');
}
?>
<?php
include('PHPMailer/PHPMailerAutoload.php');
//include('PHPExcel.php');
include('mail.php');

$mail->Subject = 'Computer Systems Report';
    $mail->Body.= 'Hi, <br><br>';
    $mail->Body.= '<table border="1">';
    $mail->Body.= '<tr>';
    $mail->Body.= '<th>Inventory Date</th>';
    $mail->Body.= '<th>Expiry Date</th>';
    $mail->Body.= '<th>Warranty</th>';
    $mail->Body.= '<th>Barcode End to End</th>';
    $mail->Body.= '<th>Assets Name</th>';
    $mail->Body.= '<th>Vendor Name</th>';
    $mail->Body.= '<th>Quantity</th>';
    $mail->Body.= '<th>Supply</th>';
    $mail->Body.= '<th>Balance</th>';
    $mail->Body.= '</tr>';
  $bsql = "SELECT * FROM dis_computer WHERE dis_status!='10'";
  $bres = mysqli_query($conn,$bsql);
  while($brow = mysqli_fetch_array($bres))
  {
    $mail->Body.= '<tr>';
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_date'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_expirdate'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_duration'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_codeseries_f'];
    $mail->Body.= " | ";
    $mail->Body.= $brow['dis_codeseries_s'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_assets'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_vendor'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_quantity'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_counter'];
    $mail->Body.= "</td>";
    $mail->Body.= "<td>";
    $mail->Body.= $brow['dis_quantity']-$brow['dis_counter'];
    $mail->Body.= "</td>";
    $mail->Body.= '</tr>';
  }
    
    $mail->Body.= '</table>';
    $mail->Body.= '<br><br><br>';
    
    $mail->Body.= '<br><br>This Report autogenerated.';
    $mail->Body.= '<br>No Signature Required.';
    if($mail->send())
    {
      header('Location:thankyou.php');
    }

?>